# run with "docker compose up"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=congestion_calculator_user
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=congestion_calculator
    ports:
      - "5433:5432"
